// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqUZJE2VUOKw1jmPZWNehcItM0TZ88EDk',
    appId: '1:539741752470:web:31763217667577035f06b7',
    messagingSenderId: '539741752470',
    projectId: 'suraj-erp-approval',
    authDomain: 'suraj-erp-approval.firebaseapp.com',
    storageBucket: 'suraj-erp-approval.firebasestorage.app',
    measurementId: 'G-XKFE67V67X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe6_gbPdrwxi4zyUlXhUJwEPq489sbG6I',
    appId: '1:539741752470:android:eeb9aa05717cb8b75f06b7',
    messagingSenderId: '539741752470',
    projectId: 'suraj-erp-approval',
    storageBucket: 'suraj-erp-approval.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZV3Uo5jhWAYt6yQWYDIW-9nJzEsskhWE',
    appId: '1:539741752470:ios:d91d9437b145406a5f06b7',
    messagingSenderId: '539741752470',
    projectId: 'suraj-erp-approval',
    storageBucket: 'suraj-erp-approval.firebasestorage.app',
    iosBundleId: 'com.suraj.surajApproval',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZV3Uo5jhWAYt6yQWYDIW-9nJzEsskhWE',
    appId: '1:539741752470:ios:18fa21292be7c6c65f06b7',
    messagingSenderId: '539741752470',
    projectId: 'suraj-erp-approval',
    storageBucket: 'suraj-erp-approval.firebasestorage.app',
    iosBundleId: 'com.example.surajApproval',
  );

}