// // Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// // for details. All rights reserved. Use of this source code is governed by a
// // BSD-style license that can be found in the LICENSE file.
//
// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
//
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//       apiKey: 'AIzaSyDCUgwBYvvzUzbsR0rBrriCK4DlHhOW3wM',
//       authDomain: 'brm-new-site.firebaseapp.com',
//       projectId: 'brm-new-site',
//       messagingSenderId: '782552886628',
//       appId: '1:782552886628:web:99275296e124c7d6ae1e71',
//       measurementId: 'G-K1VYBBZKY4'
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA5oWtSu5fg6sQaP0JfdxJ1tiVn9YP8nws',
//     appId: '1:238773939549:android:1b90ad3405b4fbba9eccb4',
//     messagingSenderId: '238773939549',
//     projectId: 'simpliworks-ad7d8',
//     // databaseURL:
//     // 'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
//     // storageBucket: 'flutterfire-e2e-tests.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyA5oWtSu5fg6sQaP0JfdxJ1tiVn9YP8nws',
//     appId: '1:238773939549:android:1b90ad3405b4fbba9eccb4',
//     messagingSenderId: '238773939549',
//     projectId: 'simpliworks-ad7d8',
//     // databaseURL:
//     // 'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
//     // storageBucket: 'flutterfire-e2e-tests.appspot.com',
//     // iosClientId:
//     // '406099696497-taeapvle10rf355ljcvq5dt134mkghmp.apps.googleusercontent.com',
//     // iosBundleId: 'io.flutter.plugins.firebase.tests',
//   );
// }